### ISSUE TITLE
Warning on Plot sigmoid in 2D Part

### ISSUE THREAD

**Issue by SilkSong** [maalvarezl/MLAI#5]
The default shading is flat, in which setting, The dimension of X and Y should be one greater than C's. In the lab 6 code, 
`plt.pcolor(gridx1, gridx2, z)` should be changed to `plt.pcolor(gridx1, gridx2, z,shading="nearest")` to dismiss the warning.
Otherwise, This will become an error two minor releases later.

**Comment by SilkSong** [comment]
I noticed that in the paragraph below, it mentioned the boundary for z = 0. I am wondering that is it better to use `contourf` to illustrate this plot more intuitively? In this way, the code above can just be modified with `plt.contourf(gridx1, gridx2, z)` without warning.

**Comment by Grey0202** [comment]
> The default shading is flat, in which setting, The dimension of X and Y should be one greater than C's. In the lab 6 code, `plt.pcolor(gridx1, gridx2, z)` should be changed to `plt.pcolor(gridx1, gridx2, z,shading="nearest")` to dismiss the warning. Otherwise, This will become an error two minor releases later.

The pyplot version in the Colab does not support **shading** as parameter.
